version: '3.8'

services:
  appointment-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
